workflows:
  flutter-app:
    name: ChAs AI Creator Build
    instance_type: linux
    working_directory: frontend
    
    environment:
      flutter: stable
    
    scripts:
      - name: Install dependencies
        script: |
          cd frontend
          flutter pub get
      
      - name: Build Android APK
        script: |
          cd frontend
          flutter build apk --release
    
    artifacts:
      - frontend/build/app/outputs/flutter-apk/app-release.apk
